spring.sql.init.platform=postgresql
db.num=1
db.url.0=jdbc:postgresql://postgres:5432/dev-nacos?currentSchema=public&reWriteBatchedInserts=true&tcpKeepAlive=true
db.user.0=postgres
db.password.0=postgres
db.pool.config.driverClassName=org.postgresql.Driver
nacos.core.auth.server.identity.key=serverIdentity
nacos.core.auth.server.identity.value=security
nacos.core.auth.plugin.nacos.token.secret.key=lVKBC8aoaFOZ4pY8TDeyl7C4td3J0V8SjVc7R+Wm3/Y=
